# ===================================================================
# Spring Boot configuration for the "heroku" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

eureka:
  instance:
    hostname: igrscms.herokuapp.com
    non-secure-port: 80
    prefer-ip-address: false

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://ec2-3-223-213-207.compute-1.amazonaws.com/d69pll7dhkncoh
    username: ximqsopwgmiudn
    password: 323fa48fcc0b707685f1126eb2b80110ccb35ed8ecfcc604cab5bac599cab7f4
    hikari:
      maximumPoolSize: 8
